
baseURL = "https://forcedpoet.gitlab.io/"
languageCode = "en-us"
title = "My Yearlong One Poetry a Day"
theme = "cupper"



[params]
	description = "This is my attampt to write Poetry every day."
	recentPostsCount = 10
	excludedTypes = ["page"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


# Enable tags.
[taxonomies]
   tag = "tags"

